version: "3.8"

services:

  accounts:
    image: deeparajndr/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - dpr-network
    
  loans:
    image: deeparajndr/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - dpr-network
    
  cards:
    image: deeparajndr/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - dpr-network
    
networks:
  dpr-network: