version: "3.8"

services:

  configserver:
    image: deeparajndr/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - dpr-network

  accounts:
    image: deeparajndr/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - dpr-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: deeparajndr/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - dpr-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: deeparajndr/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - dpr-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  dpr-network:
